### ISSUE TITLE
Heroku procfile

### ISSUE THREAD

**Issue by onuar** [msusur/shopio#18]
I'm not sure but I think, Heroku already runs npm install while deploying. "npm install" is not necessary in Procfile.

**Comment by msusur** [comment]
As far as I understand it's a file that runs while initialising your dynos. Following quote from [documentation](https://devcenter.heroku.com/articles/procfile). 

> A Procfile is a mechanism for declaring what commands are run by your application’s dynos on the Heroku platform.
